mkdir PLUGIN_DEP_INSTALL
export DEPS_INSTALL=$PWD/PLUGIN_DEP_INSTALL
mkdir PLUGIN_DEP_SRC
export SRC_DIR=$PWD/PLUGIN_DEP_SRC
export CMAKE_PREFIX="-DCMAKE_INSTALL_PREFIX=$DEPS_INSTALL"
export LD_LIBRARY_PATH="$DEPS_INSTALL/lib:$LD_LIBRARY_PATH"

export PKG_CONFIG_PATH="${DEPS_INSTALL}/lib/pkgconfig:$DEPS_INSTALL/lib/pkgconfig:$PKG_CONFIG_PATH"
export LDFLAGS="$LDFLAGS -Wl,-rpath-link=$DEPS_INSTALL/lib" 
export C_INCLUDE_PATH=$DEPS_INSTALL/include
export CPLUS_INCLUDE_PATH=$DEPS_INSTALL/include
export LIBRARY_PATH=$DEPS_INSTALL/lib
export PATH=$DEPS_INSTALL/bin:$PATH
export NUM_THREADS="-j24"

export LD_LIBRARY_PATH=$DEPS_INSTALL/lib:$DEPS_INSTALL/lib64:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$DEPS_INSTALL/lib/pkgconfig:$DEPS_INSTALL/lib64/pkgconfig
export C_INCLUDE_PATH=$DEPS_INSTALL/include
export CPLUS_INCLUDE_PATH=$DEPS_INSTALL/include
